dist: trusty
language: python
python:
  - '3.6'
before_install:
  - pip install codecov
  - pip install pipenv
install:
  - cd server && pipenv install --system && cd ..
script:
  - pytest --cov polymath.core server/tests
